# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Gray Matter
tagline:          'Thoughts by Gray'
description:      'TODO - add a description'

author:
  name:           'Gray Kemmey'
  url:            http://graykemmey.me

plugins:          ['jekyll-paginate', 'jekyll-gist']
paginate:         5
